apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-06T17:29:11Z"
  name: carts-primary
  resourceVersion: "143481"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: f26ddcdb-00ba-11ea-ac41-3ae8439df478
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts-primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
