apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-06T17:24:00Z"
  name: carts-canary
  resourceVersion: "142886"
  selfLink: /api/v1/namespaces/sockshop-staging/services/carts
  uid: 38864d34-00ba-11ea-ac41-3ae8439df478
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
